import { Link } from 'react-router-dom'
import { Flame, Sun, Zap, ClipboardList, ArrowRight } from 'lucide-react'

const calculators = [
  {
    path: '/hashrate',
    title: 'Hashrate Heating',
    description: 'Quick KPIs for hashrate heating economics. Calculate your COPe (Coefficient of Performance - Economic) and compare heating costs vs traditional fuels.',
    icon: Flame,
    color: 'bg-orange-500',
    complexity: 'Simple',
  },
  {
    path: '/solar',
    title: 'Solar Mining',
    description: 'Estimate Bitcoin mining potential from your solar system. See annual production, mining revenue, and compare excess solar value: grid credits vs BTC.',
    icon: Sun,
    color: 'bg-yellow-500',
    complexity: 'Simple',
  },
  {
    path: '/combined',
    title: 'Heat + Solar',
    description: 'Combined analysis for buildings with both heating needs and solar production. Seasonal duty cycle optimization and year-round economic projections.',
    icon: Zap,
    color: 'bg-blue-500',
    complexity: 'Combined',
  },
  {
    path: '/audit',
    title: 'Exergy Audit',
    description: 'Comprehensive energy analysis. Analyze heat loss from utility bills or building specs, get miner sizing recommendations, and detailed ROI projections.',
    icon: ClipboardList,
    color: 'bg-purple-500',
    complexity: 'Comprehensive',
  },
]

export default function Home() {
  return (
    <div className="space-y-12">
      {/* Hero Section */}
      <div className="text-center max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold text-surface-900 mb-4">
          Hashrate Heating Calculators
        </h1>
        <p className="text-lg text-surface-600">
          Make informed decisions about your hashrate heating investment.
          Start with simple KPIs or dive deep with comprehensive analysis.
        </p>
      </div>

      {/* Calculator Cards */}
      <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
        {calculators.map((calc) => {
          const Icon = calc.icon
          return (
            <Link
              key={calc.path}
              to={calc.path}
              className="group bg-white rounded-xl border border-surface-200 p-6 hover:shadow-lg hover:border-primary-200 transition-all duration-300"
            >
              <div className="flex items-start justify-between mb-4">
                <div className={`${calc.color} w-12 h-12 rounded-lg flex items-center justify-center`}>
                  <Icon className="w-6 h-6 text-white" />
                </div>
                <span className={`text-xs font-medium px-2 py-1 rounded-full ${
                  calc.complexity === 'Simple' ? 'bg-green-100 text-green-700' :
                  calc.complexity === 'Combined' ? 'bg-blue-100 text-blue-700' :
                  'bg-purple-100 text-purple-700'
                }`}>
                  {calc.complexity}
                </span>
              </div>
              <h2 className="text-xl font-semibold text-surface-900 mb-2 group-hover:text-primary-600 transition-colors">
                {calc.title}
              </h2>
              <p className="text-surface-600 text-sm mb-4">
                {calc.description}
              </p>
              <div className="flex items-center text-primary-600 font-medium text-sm">
                Open Calculator
                <ArrowRight className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform" />
              </div>
            </Link>
          )
        })}
      </div>

      {/* Info Section */}
      <div className="bg-primary-50 rounded-xl p-8 text-center">
        <h2 className="text-2xl font-semibold text-surface-900 mb-4">
          What is Hashrate Heating?
        </h2>
        <p className="text-surface-700 max-w-2xl mx-auto mb-6">
          Hashrate heating uses Bitcoin mining hardware to heat your home or business
          while earning Bitcoin. The heat generated by mining is 100% efficient —
          every watt of electricity becomes heat, plus you earn cryptocurrency.
        </p>
        <a
          href="https://exergyheat.com/learn"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 bg-primary-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-primary-700 transition-colors"
        >
          Learn More at Exergy
          <ArrowRight className="w-4 h-4" />
        </a>
      </div>
    </div>
  )
}
