import { Link } from 'react-router-dom'
import { ArrowRight } from 'lucide-react'
import { calculators, externalLinks, externalLinkClass } from '../data/calculators'
import SEO from '../components/SEO'

export default function Home() {
  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Exergy Calculators - Bitcoin Mining Economics',
    description: 'Free calculators for Bitcoin mining economics: hashrate heating and solar monetization analysis.',
    url: 'https://webapp-calculators.example.com',
  }

  return (
    <div className="space-y-8 sm:space-y-12">
      <SEO
        title="Bitcoin Mining Calculators"
        description="Free calculators for Bitcoin mining economics. Analyze hashrate heating efficiency (COPe) and solar mining profitability with real-time BTC network data."
        keywords="bitcoin mining calculator, hashrate heating, solar mining, COPe calculator, bitcoin economics, mining profitability"
        canonical="/"
        structuredData={structuredData}
      />

      {/* Hero Section */}
      <div className="text-center max-w-3xl mx-auto px-2">
        <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-surface-900 dark:text-surface-100 mb-3 sm:mb-4">
          Exergy Calculators
        </h1>
        <p className="text-sm sm:text-base md:text-lg text-surface-600 dark:text-surface-400">
          Investigate the economics of mining bitcoin for heat or solar monetization.
        </p>
      </div>

      {/* Calculator Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
        {calculators.map((calc) => {
          const Icon = calc.icon
          return (
            <Link
              key={calc.path}
              to={calc.path}
              className="group block bg-white dark:bg-surface-800 rounded-xl p-6 shadow-lg hover:shadow-xl hover:scale-[1.02] transition-all duration-300"
            >
              <div className="flex items-center gap-4 mb-4">
                <div className={`${calc.color} w-12 h-12 rounded-lg flex items-center justify-center`}>
                  <Icon className="w-6 h-6 text-white" />
                </div>
                <h2 className="text-lg sm:text-xl font-semibold text-surface-900 dark:text-surface-100 group-hover:text-primary-600 dark:group-hover:text-primary-400 transition-colors">
                  {calc.title}
                </h2>
              </div>
              <p className="text-surface-600 dark:text-surface-400 text-sm mb-4">
                {calc.description}
              </p>
              <div className="flex items-center text-primary-600 dark:text-primary-400 font-medium text-sm">
                <span>Open Calculator</span>
                <ArrowRight className="w-4 h-4 ml-2 group-hover:translate-x-1 transition-transform" />
              </div>
            </Link>
          )
        })}
      </div>

      {/* Info Section */}
      <div className="text-center">
        <h2 className="text-lg sm:text-2xl font-semibold text-surface-900 dark:text-surface-100 mb-2 sm:mb-4">
          What is Hashrate Heating?
        </h2>
        <p className="text-sm sm:text-base text-surface-700 dark:text-surface-300 max-w-2xl mx-auto mb-4 sm:mb-6">
          Hashrate heating uses bitcoin mining hardware to electrically heat your home or business while earning revenue. The heat generated by mining is 100% efficient —
          every watt of electricity becomes heat, plus you earn bitcoin.
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-6 max-w-3xl mx-auto">
          {externalLinks.map((link) => {
            const Icon = link.icon
            return (
              <a
                key={link.href}
                href={link.href}
                target="_blank"
                rel="noopener noreferrer"
                className={externalLinkClass}
              >
                <Icon className="w-8 h-8 text-primary-600 dark:text-primary-400" />
                <span className="text-sm sm:text-base font-medium text-surface-700 dark:text-surface-300">{link.label}</span>
              </a>
            )
          })}
        </div>
      </div>
    </div>
  )
}
